quarkus.container-image.name=airhacks-apprunner-service
quarkus.container-image.group=airhacks
quarkus.container-image.push=true
quarkus.container-image.tag=latest
quarkus.container-image.registry=${CDK_DEFAULT_ACCOUNT:uknown}.dkr.ecr.eu-west-1.amazonaws.com