sns.greetings.topic=arn:aws:sns:${CDK_DEFAULT_REGION:java}:${CDK_DEFAULT_ACCOUNT:42}:greetings
quarkus.sns.aws.region=${CDK_DEFAULT_REGION:java}
quarkus.sns.aws.credentials.type=profile
quarkus.sns.aws.credentials.profile-provider.profile-name=cli