quarkus.container-image.name=ecs-fargate-quarkus
quarkus.container-image.group=airhacks
quarkus.container-image.push=true
quarkus.container-image.tag=latest
quarkus.container-image.registry=${CDK_DEFAULT_ACCOUNT:42}.dkr.ecr.${CDK_DEFAULT_REGION:eu-central-1}.amazonaws.com